ASPNETCORE_MVC_WEBAPI/ASPNETCOREMVC/Controllers/FormularDemoController.cs
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace ASPNETCOREMVC.Controllers
{
    public class FormularDemoController : Controller
    {


        [HttpGet]
        public IActionResult Sample1() //Zeigt das Formular
        {
            return View();
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Sample1(string myText, int myNumber) //Parametervarialen müssen den selbe Benennung aufweisen, wie in  <input>-Tag - Attribut Name: 
        {

            return RedirectToAction("Sample2", new { myText = myText, myNumber = myNumber } );
        }


        public IActionResult Sample2(string myText, int MyNumber)
        {
            MyLinkValues myValues = new MyLinkValues();
            myValues.Name = myText;
            myValues.Zahl = MyNumber;

            return View(myValues);
        }



        public IActionResult Index()
        {
            return View();
        }

        [HttpPost]
        public IActionResult Index(string firstName, string lastName)
        {
            ViewBag.Name = string.Format("Name: {0} {1}", firstName, lastName);
            return RedirectToAction("Index");
        }


        public IActionResult Sample3 ()
        {
            return View();
        }

        [HttpPost]
        public IActionResult RegisterAny(string myText, int MyNumber)
        {
            return RedirectToAction(nameof(Index));
        }

        [HttpPost]
        public IActionResult DoAnything(string myText, int MyNumber)
        {
            return RedirectToAction(nameof(Index));
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Sample3(string myText, int myNumber) //Parametervarialen müssen den selbe Benennung aufweisen, wie in  <input>-Tag - Attribut Name: 
        {

            return RedirectToAction("Sample2", new { myText = myText, myNumber = myNumber });
        }
    }


    public class MyLinkValues
    {
        public string Name { get; set; }
        public int Zahl { get; set; }
    }
}

ASPNETCORE_MVC_WEBAPI/ASPNETCOREMVC/Views/FormularDemo/Index.cshtml
@{
    ViewData["Title"] = "Index";
}

<h1>Index</h1>

<form method="post" enctype="multipart/form-data" asp-controller="FormularDemo" asp-action="Index">
    <table>
        <tr>
            <td>First Name: </td>
            <td><input type="text" id="txtFirstName" name="FirstName" /></td>
        </tr>
        <tr>
            <td>Last Name: </td>
            <td><input type="text" id="txtLastName" name="LastName" /></td>
        </tr>
        <tr>
            <td></td>
            <td><input type="submit" value="Submit" /></td>
        </tr>
    </table>
    <hr />
    @ViewBag.Name
</form>

ASPNETCORE_MVC_WEBAPI/ASPNETCOREMVC/Views/FormularDemo/Sample1.cshtml
@{
    ViewData["Title"] = "Sample1";
}

<h1>Sample1</h1>


<p>Ein Formular mit einem Button</p>

<form method="post">
    <input type="text" id="txtMyName" name="myText" />
    <input type="number" id="intMyNumber" name="myNumber"/>
    <input type="submit" value="Senden an Post-Methode" />
</form>

ASPNETCORE_MVC_WEBAPI/ASPNETCOREMVC/Views/FormularDemo/Sample2.cshtml
@model ASPNETCOREMVC.Controllers.MyLinkValues

@{
    ViewData["Title"] = "Sample2";
}

<h1>Sample2</h1>

<div>
    <h4>MyLinkValues</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Name)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Name)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Zahl)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Zahl)
        </dd>
    </dl>
</div>
<div>
    @Html.ActionLink("Edit", "Edit", new { /* id = Model.PrimaryKey */ }) |
    <a asp-action="Index">Back to List</a>
</div>

ASPNETCORE_MVC_WEBAPI/ASPNETCOREMVC/Views/FormularDemo/Sample3.cshtml
@{
    ViewData["Title"] = "Sample3";
}

<h1>Sample3</h1>

<form method="post">
    <input type="text" id="txtMyName" name="myText" />
    <input type="number" id="intMyNumber" name="myNumber" />


    <input type="submit" asp-action="RegisterAny" value="Registriere" />
    <input type="submit" asp-action="DoAnything" value="Mach Irgendwas" />
</form>


<form method="post">
    <input type="text" id="txtMyName" name="myText" />
    <input type="number" id="intMyNumber" name="myNumber" />
    <input type="submit" value="Senden an Post-Methode" />
</form>