ASPNETCORE_MVC_WEBAPI/ASPNETCOREMVC/Controllers/DemoController.cs
using ASPNETCOREMVC.Models;
using ASPNETCOREMVC.ViewModels;
using DependencyInversionSample;
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace ASPNETCOREMVC.Controllers
{
    public class DemoController : Controller
    {
        private readonly IMockCar _car;

        public DemoController(IMockCar car)
        {
            _car = car;
        }

        public IActionResult Sample1()
        {
            return View(_car);
        }

        public IActionResult Sample2()
        {
            Product product = new Product()
            {
                Id = 123,
                Name = "Haribo",
                Preis = 11.99m
            };

            return View(product);
        }

        public IActionResult Sample3()
        {
            var products = new List<Product>()
            {
                new Product()
                {
                    Id = 1,
                    Name = "Playstation 5",
                    Preis = 499.95m
                },
                new Product()
                {
                    Id = 2,
                    Name = "XBox",
                    Preis = 199m
                },
                new Product()
                {
                    Id = 3,
                    Name = "Nitendo Switch",
                    Preis = 300m
                }
            };

            return View(products);
        }

        //Diese MEthode ist nur mit ID verwendbar
        public IActionResult Sample4(int? id)
        {

            if (!id.HasValue)
                return NotFound(); //404 Fehler wird ausgegeben, wenn die Id Leer ist 

            Product product = new Product()
            {
                Id = id.Value,
                Name = "Haribo",
                Preis = 11.99m
            };

            return View(product);
        }

        public IActionResult SampleWithViewModel()
        {
            RegisseurStatVM regisseurStat = new RegisseurStatVM();

            if (regisseurStat.Regisseur == null)
                regisseurStat.Regisseur = new Regisseur();

            regisseurStat.Regisseur.Id = 123;
            regisseurStat.Regisseur.Name = "Steven Spielberg";

            regisseurStat.MovieList = new List<Movie>();
            regisseurStat.MovieList.Add(new Movie
            {
                Id = 1,
                Title = "ES",
                Description = "Film mit Clown",
                Price = 12.99m
            });
            regisseurStat.MovieList.Add(new Movie
            {
                Id = 2,
                Title = "Jurassic Park",
                Description = "Bitte nicht den T-Rex selbständig füttern",
                Price = 13.99m
            });
            regisseurStat.MovieList.Add(new Movie
            {
                Id = 3,
                Title = "Donald Duck",
                Description = "Abenteuer in Entenhausen",
                Price = 2.99m
            });

            regisseurStat.FouvriteActos = new List<Actors>();
            regisseurStat.FouvriteActos.Add(new Actors()
            {
                Id = 1,
                Name = "Cameron Diaz"
            });
            regisseurStat.FouvriteActos.Add(new Actors()
            {
                Id = 2,
                Name = "Brad Pitt"
            });

            return View(regisseurStat);
        }


        public IActionResult RoutValuesWithQueryStringSample()
        {
            return View();
        }

        //Call mit QueryString -> https://localhost:5001/Demo/QueryStringDemo?id=1&name=harry
        public IActionResult QueryStringDemo(int? id, string name)
        {
            return View();
        }


        [Route("sample5/{fullName}/{zahldesTages}")]
        public IActionResult Sample5(string fullName, int zahldesTages)
        {
            return View();
        }
    }
}

ASPNETCORE_MVC_WEBAPI/ASPNETCOREMVC/Controllers/MovieController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using ASPNETCOREMVC.Data;
using ASPNETCOREMVC.Models;
using Microsoft.AspNetCore.Http;
using System.Text.Json;

namespace ASPNETCOREMVC.Controllers
{
    public class MovieController : Controller
    {
        private readonly MovieDbContext _context;

        public MovieController(MovieDbContext context)
        {
            _context = context;
        }

        // GET: Movie
        public async Task<IActionResult> Index(string query)
        {
            if (!string.IsNullOrEmpty(query))
            {
                ViewData["FilterQuery"] = query;
            }

            IList<Movie> filteredList = string.IsNullOrEmpty(query) ?
                await _context.Movie.ToListAsync() :
                await _context.Movie.Where(q => q.Title.Contains(query)).ToListAsync();

            return View(filteredList);
        }

        // GET: Movie/Details/5
        [HttpGet("/movie/details/{id}")]
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var movie = await _context.Movie
                .FirstOrDefaultAsync(m => m.Id == id);
            if (movie == null)
            {
                return NotFound();
            }

            return View(movie);
        }

        // GET: Movie/Create
        //[Route("/movie/create")]
        [HttpGet("/movie/create")]
        public IActionResult Create()
        {
            return View();
        }

        // POST: Movie/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost("/movie/create")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("Id,Title,Description,Genre,Price")] Movie movie)
        {
            if (movie.Title == "Platoon")
            {
                ModelState.AddModelError("FSK18", "FSK Warning: Film zeigt unangbrachten Inhalt");
                ModelState.AddModelError("Title", "Film zeigt unangbrachten Inhalt");
            }


            if (ModelState.IsValid)
            {
                _context.Add(movie);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            return View(movie);
        }

        // GET: Movie/Edit/
        [HttpGet("/movie/edit/{id}")]
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var movie = await _context.Movie.FindAsync(id);
            if (movie == null)
            {
                return NotFound();
            }
            return View(movie);
        }

        // POST: Movie/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost("/movie/edit/{id}")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("Id,Title,Description,Genre,Price")] Movie movie)
        {
            if (id != movie.Id)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(movie);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!MovieExists(movie.Id))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(movie);
        }

        // GET: Movie/Delete/5
        [HttpGet("/movie/delete/{id}")]
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var movie = await _context.Movie
                .FirstOrDefaultAsync(m => m.Id == id);
            if (movie == null)
            {
                return NotFound();
            }

            return View(movie);
        }

        // POST: Movie/Delete/5
        [HttpPost("/movie/Delete/{id}"), ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var movie = await _context.Movie.FindAsync(id);
            _context.Movie.Remove(movie);
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool MovieExists(int id)
        {
            return _context.Movie.Any(e => e.Id == id);
        }

        [HttpPost("/movie/buy/{id}")]
        public IActionResult Buy(int? id)
        {


            if (!id.HasValue)
                return BadRequest();

            if (HttpContext.Session.IsAvailable)
            {
                List<int> idList = new List<int>();

                //Gibt es schon einen Warenkorb Objekt für meine Session 
                if (HttpContext.Session.Keys.Contains("ShoppingCart"))
                {
                    //Wenn ja, wurde schon einmal was gekauft und der Session-Eintrag exisitiert

                    string jsonIdList = HttpContext.Session.GetString("ShoppingCart");

                    //befüllte idList mit existierenden Einkäufe
                    idList = JsonSerializer.Deserialize<List<int>>(jsonIdList);
                }

                idList.Add(id.Value);

                string jsonString = JsonSerializer.Serialize(idList);

                HttpContext.Session.SetString("ShoppingCart", jsonString);
            }


            return RedirectToAction(nameof(Index));
        }
    }
}

ASPNETCORE_MVC_WEBAPI/ASPNETCOREMVC/Controllers/ShoppingPaymentController.cs
using ASPNETCOREMVC.Data;
using ASPNETCOREMVC.Models;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text.Json;
using System.Threading.Tasks;

namespace ASPNETCOREMVC.Controllers
{
    public class ShoppingPaymentController : Controller
    {
        private readonly MovieDbContext _context;

        public ShoppingPaymentController(MovieDbContext context)
        {
            _context = context;
        }

        public IActionResult ShoppingCartOverview()
        {
            List<Movie> movieList = new List<Movie>();

            if (HttpContext.Session.IsAvailable)
            {
                if (HttpContext.Session.Keys.Contains("ShoppingCart"))
                {
                    movieList = InitializeShoppingCart();
                }
            }

            return View(movieList);
        }

        private List<Movie> InitializeShoppingCart()
        {
            List<Movie> movieList = new List<Movie>();

            string shoppingCartJsonString = HttpContext.Session.GetString("ShoppingCart");
            List<int> ids = JsonSerializer.Deserialize<List<int>>(shoppingCartJsonString);


            foreach(int currentArticleId in ids)
            {
                Movie currentMovie = _context.Movie.Find(currentArticleId);
                movieList.Add(currentMovie);
            }



            return movieList;

        }


        [HttpPost]
        public IActionResult Delete(int? id)
        {
            if (!id.HasValue)
                return BadRequest();

            List<Movie> movies = InitializeShoppingCart();

            //Wird geprüft, ob die ArtikelId sich im Warenkorb befindet
            if (movies.Any(a => a.Id == id.Value))
            {
                Movie toCancel = movies.First(a => a.Id == id.Value);

                movies.Remove(toCancel);

                if (movies.Count == 0)
                {
                    HttpContext.Session.Remove("ShoppingCart");
                }
                else
                {
                    string jsonString = JsonSerializer.Serialize(movies.Select(n => n.Id).ToList());

                    HttpContext.Session.SetString("ShoppingCart", jsonString);
                }
            }

            return RedirectToAction(nameof(ShoppingCartOverview));
        }


        public IActionResult Payment()
        {
            return View();
        }


        //[AllowAnonymous] //In dieser Methode dürfen alle User oder Unbekannte darauf zugreifen
        //public IActionResult AllCanAccess()
        //{
        //    return View();
        //}

        //[Authorize("Admins")]
        //[Authorize("Support")]
        //public IActionResult OnlyAdmins()
        //{
        //    return View();
        //}


    }
}

ASPNETCORE_MVC_WEBAPI/ASPNETCOREMVC/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - ASPNETCOREMVC</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm bg-dark navbar-dark">
            <!-- Brand -->
            <a class="nav-link" asp-controller="Home" asp-action="Index">Home</a>

            <!-- Links -->
            <ul class="navbar-nav">
                <li class="nav-item">
                    <a class="nav-link" asp-controller="Home" asp-action="Index">Home</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" asp-controller="Home" asp-action="Privacy">Privacy</a>
                </li>

                <li class="nav-item">
                    <a class="nav-link" asp-controller="Movie" asp-action="Index">Movie</a>
                </li>

                <li class="nav-item">
                    <a class="nav-link" asp-controller="ShoppingPayment" asp-action="ShoppingCartOverview">Warenkorb Übersicht</a>
                </li>


                <!-- Dropdown -->
                <li class="nav-item dropdown">
                    <a class="nav-link dropdown-toggle" href="#" id="navbardrop" data-toggle="dropdown">
                        Demo-Beispiele
                    </a>
                    <div class="dropdown-menu">
                        <a class="dropdown-item" asp-controller="Demo" asp-action="Sample1">Sample1</a>
                        <a class="dropdown-item" asp-controller="Demo" asp-action="Sample2">Sample2</a>
                        <a class="dropdown-item" asp-controller="Demo" asp-action="Sample3">Sample3</a>
                    </div>
                </li>
            </ul>
            <partial name="_LoginPartial" />
            <vc:cultur-switcher />
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody() <!-- Hoier werden die Views aufgelöst-->
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2021 - ASPNETCOREMVC - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>

ASPNETCORE_MVC_WEBAPI/ASPNETCOREMVC/Views/Shared/_Layout2.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - ASPNETCOREMVC</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />
</head>
<body style="background-color:orange">
    <header>
        <nav class="navbar navbar-expand-sm bg-dark navbar-dark">
            <!-- Brand -->
            <a class="nav-link" asp-controller="Home" asp-action="Index">Home</a>

            <!-- Links -->
            <ul class="navbar-nav">
                <li class="nav-item">
                    <a class="nav-link" asp-controller="Home" asp-action="Index">Home</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" asp-controller="Home" asp-action="Privacy">Privacy</a>
                </li>

                <li class="nav-item">
                    <a class="nav-link" asp-controller="ShoppingPayment" asp-action="ShoppingCartOverview">Warenkorb Übersicht</a>
                </li>

                <!-- Dropdown -->
                <li class="nav-item dropdown">
                    <a class="nav-link dropdown-toggle" href="#" id="navbardrop" data-toggle="dropdown">
                        Demo-Beispiele
                    </a>
                    <div class="dropdown-menu">
                        <a class="dropdown-item" asp-controller="Demo" asp-action="Sample1">Sample1</a>
                        <a class="dropdown-item" asp-controller="Demo" asp-action="Sample2">Sample2</a>
                        <a class="dropdown-item" asp-controller="Demo" asp-action="Sample3">Sample3</a>
                    </div>
                </li>
            </ul>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody() <!-- Hoier werden die Views aufgelöst-->
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2021 - ASPNETCOREMVC - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>

ASPNETCORE_MVC_WEBAPI/ASPNETCOREMVC/Views/Shared/_SpecialOfferPartialView.cshtml
@model IEnumerable<ASPNETCOREMVC.Models.Movie>
@*
    For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860
*@
@{
    Movie movieWithLowestPrice = null;

    if (Model.Any())
    {
        movieWithLowestPrice = Model.OrderBy(o => o.Price).First();
    }
}

@if (movieWithLowestPrice != null)
{
    <p>Sonderangebot</p>
    <div class="card" style="background-color: darkorange">
        <div class="card-body">
            <p>@movieWithLowestPrice.Title</p>
            <p>@movieWithLowestPrice.Price</p>
        </div>
    </div>
}
else
{
    <p>Aktuell kein Sonderangebot aus gefilterten Sortiment verfügbar</p>
}

ASPNETCORE_MVC_WEBAPI/ASPNETCOREMVC/Views/Shared/_Zeit.cshtml
@*
    For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860
*@
@{
}

@DateTime.Now;